list: $/meysam/test/models/word/columns.yaml
modelClass: Meysam\Test\Models\Word
title: Words
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'meysam/test/words/update/:id'
