list: $/meysam/test/models/story/columns.yaml
modelClass: Meysam\Test\Models\Story
title: Stories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'meysam/test/stories/update/:id'
recordOnClick: "$.popup({ handler: 'onLoadWordForm', extraData: { record_id: ':id' } })"
